fs = 8e3;
tf = 0.4;
tp = 0;
th = tf/2;
soundnote('F',5,0,tf,fs,tp);
soundnote('F',5,0,th,fs,tp);
soundnote('F',6,0,th,fs,tp);
soundnote('F',2,0,2*tf,fs,tp);
% pause(tp);
soundnote('F',1,0,tf,fs,tp);
soundnote('F',1,0,th,fs,tp);
soundnote('F',-1,0,th,fs,tp);
soundnote('F',2,0,2*tf,fs,tp);
% pause(tp);