fs = 8e3;
tf = 0.5;
tp = 0.5;
th = tp/2;
soundnote('F',5,0,tf,fs,tp);
soundnote('F',5,0,th,fs,th);
soundnote('F',6,0,th,fs,th);
soundnote('F',2,0,tf,fs,tp);
pause(tp);
soundnote('F',1,0,tf,fs,tp);
soundnote('F',1,0,th,fs,th);
soundnote('F',-1,0,th,fs,th);
soundnote('F',2,0,tf,fs,tp);
pause(tp);